title: Project Iceberg
logo: /imgs/logo.png
description: An agglomerate of posts on Statistics, Machine Learning and Deep Learning.
theme: jekyll-theme-minimal
google_analytics: UA-179093993-1
plugins:
  - jekyll-sitemap